# API listening port
#port: 8080

# TLS/SSL Settings.  Leave to default unless you want to provide your own TLS certificate.
#tls_cert_file: "cert.crt"
#tls_key_file:  "cert.key"
tls_directory: "/etc/pki/tls/certs/tism"

# Path to PGP/GPG keyring file.
keyring_path: "/var/lib/tism/secring.gpg"

# token_secret The secret used to sign all JWT tokens.  If this is changed all previosly signed tokens will become invalid.
token_secret: {{.TokenSecret}}

# revoked_tokens list of revoked tokens.
#revoked_tokens:
#  - 12341234123412
